spring.application.name=inventory-control

# H2 database configuration
spring.datasource.url=jdbc:h2:mem:inventoryDB
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=adminInventory
spring.datasource.password=

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

# Show SQL in console (optional)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# H2 web console (optional)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
